### ISSUE TITLE
Why does the NA12878 reference fail when comparing it with itself?

### ISSUE THREAD

**Issue by marizazh** [ywchoi/phasing#2]
I am trying to do something very simple before using phasing on my data:

1. I git cloned the project.
2. I downloaded the NA12878 reference from nih.gov
3. then I ran `$ ./scripts/measure_phasing_performance.pl -i examples/chr20.vcf.gz -r gold_standard/chr20.snp.vcf.gz -o examples/test` which seems to work
4. When I try to run `./scripts/measure_phasing_performance.pl -i ./NIST_RTG_PlatGen_merged_highconfidence_v0.2_Allannotate.vcf.gz -r NIST_RTG_PlatGen_merged_highconfidence_v0.2_Allannotate.vcf.gz
-o example/test` it fails:
```
Non-SNP variant exists: 1	723798	.	CAG	C	23974	PASS	DPSum=677;HRun=0;HapNoVar=0;NoPLTot=0;PL454WG=450,30,0;PLCG=591,11,0;PLHSWG=2674,184,0;PLILL250=1680,118,0;PLILLCLIA=4551,307,0;PLILLWG=1834,132,0;PLIllPCRFree=2028,137,0;PLNCIIonWG=171,12,0;PLPlatGen=8211,560,0;PLXIll=1172,79,0;PLXPSolWGLS=612,43,0;PLminsum=1613;PLminsumOverDP=2.38;RPA=10,9,11;RU=AATGG;TrancheABQDmin2=0;TrancheAlignmin2=0;TrancheMapmin2=0;TrancheSSEmin2=0;YesPLtot=9;allalts=C;callers=bwa,isaac,cgi;datasetcalls=11;editDistance=5;geno=3;genoMapGood=9;isPolymorphic=0;platformbias=none;platformnames=ill,454,sol;platforms=3;source=NISTPASS,PlatGen;varType=INDEL	GT:DP:GQ:PL	1/1:677:1613:23974,1613,0
```

Can you suggest what you do please? My end goal is to compare the nih.gov NA12878 reference with the same sample phased haplotype with HapCUT2.

Thank you so much.

**Comment by ywchoi** [comment]
Hello. It showed the error message because there is a non-SNP variant (i.e. a deletion in this case). The script assumes that the VCF file has only SNPs.
