### ISSUE TITLE
QAN50 metric

### ISSUE THREAD

**Issue by kevyin** [ywchoi/phasing#3]
Hi there

Am just checking if I'm interpreting the code correctly.

Is the QAN50 number not calculated by the script at the moment but something we can calculate from the "ADJUSTED_LENGTH" column in the QBL table?

Thanks

**Comment by ywchoi** [comment]
Hi,
Yes. QAN50 needs to be calculated based on the ADJUSTED_LENGTH values in the same way as the usual assembly statistic N50.

**Comment by kevyin** [comment]
Thanks
